- name: Creación routing EIGRP en switches de core
  hosts: "{{ modelo.hosts_groups.core_switches }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - name: Define variables para plantillas
      ansible.builtin.set_fact:
        routing: "{{ modelo.infra_spec.devices[inventory_hostname].routing }}"
      register: set_device_vars

    - name: Render EIGRP configuration
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/eigrp_{{item.type}}.j2"
        dest: "{{ playbook_dir }}/{{item.path_d}}/{{item.beg}}{{ inventory_hostname }}_eigrp.{{item.ext}}"
        mode: '0644'
      loop:
        - {path_d: "../configs", ext: cfg, type: cfg, beg: ''}
        - {path_d: "../documentacion/modulos", ext: md, type: doc, beg: '1.5'}
      register: render_eigrp

- name: Creación de configuración interfaces de acceso en switches de acceso
  hosts: "{{ modelo.hosts_groups.access_switches, modelo.hosts_groups.data_center_switches }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - name: Define variables para plantillas
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"
      register: set_device_vars

    - name: Render access interfaces configuration
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/inter_access_{{item.type}}.j2"
        dest: "{{ playbook_dir }}/{{item.path_d}}/{{item.beg}}{{ inventory_hostname }}_interfaces_access.{{item.ext}}"
        mode: '0644'
      loop:
        - {path_d: "../configs", ext: cfg, type: cfg, beg: ''}
        - {path_d: "../documentacion/modulos", ext: md, type: doc, beg: '1.3'}
      register: render_inter_access

- name: Creación de configuración interfaces svi en switches de core
  hosts: "{{ modelo.hosts_groups.core_switches }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - name: Define variables para plantillas
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"
      register: set_device_vars

    - name: Render svi interfaces configuration
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/inter_svi_{{item.type}}.j2"
        dest: "{{ playbook_dir }}/{{item.path_d}}/{{item.beg}}{{ inventory_hostname }}_interfaces_svi.{{item.ext}}"
        mode: '0644'
      loop:
        - {path_d: "../configs", ext: cfg, type: cfg, beg: ''}
        - {path_d: "../documentacion/modulos", ext: md, type: doc, beg: '1.2'}
      register: render_inter_svi

- name: Creación de configuración interfaces trunk en switches de acceso
  hosts: "{{ modelo.hosts_groups.access_switches, modelo.hosts_groups.core_switches, modelo.hosts_groups.data_center_switches }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - name: Define variables para plantillas
      ansible.builtin.set_fact:
        interfaces: "{{ modelo.infra_spec.devices[inventory_hostname].interfaces }}"
      register: set_device_vars

    - name: Render trunk interfaces configuration
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/inter_trunk_{{item.type}}.j2"
        dest: "{{ playbook_dir }}/{{item.path_d}}/{{item.beg}}{{ inventory_hostname }}_interfaces_trunk.{{item.ext}}"
        mode: '0644'
      loop:
        - {path_d: "../configs", ext: cfg, type: cfg, beg: ''}
        - {path_d: "../documentacion/modulos", ext: md, type: doc, beg: '1.4'}
      register: render_inter_trunk

- name: Creación de configuración de VLANs en todos los switches
  hosts: "{{ modelo.hosts_groups.access_switches, modelo.hosts_groups.core_switches, modelo.hosts_groups.data_center_switches }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - name: Define variables para plantillas
      ansible.builtin.set_fact:
        vlans: "{{ modelo.infra_spec.devices[inventory_hostname].vlans }}"
      register: set_device_vars

    - name: Render VLANs configuration
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/vlans_{{item.type}}.j2"
        dest: "{{ playbook_dir }}/{{item.path_d}}/{{item.beg}}{{ inventory_hostname }}_vlans.{{item.ext}}"
        mode: '0644'
      loop:
        - {path_d: "../configs", ext: cfg, type: cfg, beg: ''}
        - {path_d: "../documentacion/modulos", ext: md, type: doc, beg: '1.1'}
      register: render_vlans

- name: Titulo Reporte de Automatización de Configuraciones de Red
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - include_tasks: ../tasks/task_timestamp.yaml 

    - name: Define variables para plantillas
      ansible.builtin.set_fact:
        servicio: "{{ modelo.metadatos.proyecto }}"
        date: "{{ date_local.stdout[0:10]}}"
        time: "{{ date_local.stdout[11:]}}"
      register: set_device_vars

    - name: Render Titulo Reporte de Automatización de Configuraciones de Red
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/titulo_reporte_{{item.type}}.j2"
        dest: "{{ playbook_dir }}/{{item.path_d}}/{{item.beg}}Titulo_reporte.{{item.ext}}"
        mode: '0644'
      loop:
        - {path_d: "../documentacion/modulos", ext: md, type: doc, beg: '1.0'}
      register: render_vlans
