# Playbook to create documentation
# By Ed Scrimaglia
---
- name: "*** Crea Documentacion ***"
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  vars:
    servicio: "{{modelo.metadatos.proyecto}}"
    reporte: 
      - "VLANs Provisioning"
      - "Interfaces SVI Provisioning"
      - "Interfaces Access Provisioning"
      - "Interfaces Trunks Provisioning"
    cant_serv: 4

  tasks:
    - include_tasks: ../tasks/task_timestamp.yaml

    - name: Set Data Model as Fact
      set_fact:
        date: "{{ date_local.stdout[0:10]}}"
        time: "{{ date_local.stdout[10:]}}"

    - include_tasks: ../tasks/task_check_empty_dir.yaml
  
    - name: Assemble all .md files y crea Documento Reporte Servicio {{servicio}}
      assemble:
        src: "{{ playbook_dir }}/../documentacion/modulos"
        dest: "{{ playbook_dir }}/../documentacion/Reporte {{ servicio }}@{{ date }} , {{ time }}.md"
        delimiter: '............................................................................................................'
        regexp: ^1
      run_once: true
      when: files_start_found.matched > 0
    