- name: Configuración routing EIGRP en switches de core
  hosts: "{{ modelo.hosts_groups.core_switches }}"
  gather_facts: false

  vars_files:
    - ../modelo_datos/modelo.yaml

  tasks:
    - name: EIGRP configuration
      cisco.ios.ios_config:
        src: "{{ playbook_dir }}/../configs/{{ inventory_hostname }}_eigrp.cfg"
      register: config_eigrp
      notify: Guardar configuración

    - name: Mostrar resultado configuración EIGRP
      ansible.builtin.debug:
        msg: "Configuracion EIGRP en dispositivo {{ inventory_hostname }} realizada exitosamente"

  handlers:
    - name: Guardar configuración
      cisco.ios.ios_config:
        save_when: modified