# Ansible group variables for Cisco IOS access devices
ansible_network_os: cisco.ios.ios
ansible_user: netsim
ansible_become: true
ansible_become_method: ansible.netcommon.enable
ansible_become_password: password