# Playbook para usar variables pertenecientes a diferentes hosts
# By Ed Scrimaglia

---
- name: Play para usar variables de otros hosts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ./modelo_datos/modelo_datos.yaml

  tasks:
    - name: Definir una variable y le asigna el valor del atributo hosts_group del Modelo de Datos
      ansible.builtin.set_fact:
        list_hosts: "{{ modelo.infra_spec.hosts_group }}"

    - name: Mostrar la variable local que contiene el grupo de hosts
      ansible.builtin.debug:
        msg: "El grupo de hosts es: {{ list_hosts }}"

- name: Play para mostrar la variable de otro host (localhost)
  hosts: "{{ hostvars['localhost'].list_hosts }}"
  gather_facts: false

  tasks:
    - name: Mostrar interfaces de cada dispositivo
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - name: Mostrar salida de interfaces
      ansible.builtin.debug:
        var: interface_output.stdout_lines
