# Ejemplo de playbook para obtener y mostrar la configuracion de dispositivos Cisco IOS
# By Ed Scrimaglia

---
- name: Playbook para ver salidas de comandos de consulta sobre dispositivos Cisco IOS de acceso
  hosts: cisco_ios
  gather_facts: false

  tasks:
    - name: Ejecutar comandos de consulta en los dispositivos de acceso
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: device_info

    - name: Mostrar informacion de los dispositivos de acceso
      ansible.builtin.debug:
        var: device_info.stdout_lines

- name: Playbook para ver salidas de comandos de consulta sobre dispositivos Cisco IOS de core
  hosts: cisco_ios_core
  gather_facts: false

  tasks:
    - name: Ejecutar comandos de consulta en los dispositivos de core
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: device_info

    - name: Mostrar informacion de los dispositivos de core
      ansible.builtin.debug:
        var: device_info.stdout_lines
