# Playbook para leer el modelo de datos y pasarlo entre Plays como variables entre hosts
# By Ed Scrimaglia

---
- name: Play para usar variables de otros hosts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ./modelo_datos/modelo_datos.yaml

  tasks:
    - name: Definir una variable y le asigna el valor del atributo hosts_group del Modelo de Datos
      ansible.builtin.set_fact:
        modelo: "{{ modelo }}"


- name: Play para mostrar la variable de otro host (localhost)
  hosts: "{{ hostvars['localhost'].modelo.infra_spec.hosts_group }}"
  gather_facts: false

  tasks:
    - name: Mostrar interfaces de cada dispositivo
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - name: Mostrar salida de interfaces
      ansible.builtin.debug:
        var: interface_output.stdout_lines
